#include <stdio.h>
#include <stdlib.h>
//bunch of characters within "" are call strings

// VARIABLES ARE PLACEHOLDERS
/* VARIABLES ARE MEMORY LOCATIONS OF BUNCH OF DATA TYPES
   IN WHICH ACTUAL DATA IS STORED */

   // RULES
   // IN NAMING THE VARIABLE FIRST LETTER SHOUDL BE0 UPPERCASE OR LOWERCASE ALPHABET
   // NUMBERS ARE NOT ALLOWED IN FIRST LETTER
   // DONT USE SYMBOLES OTHER THAN UNDERSCORE
   // DO NOT NAME IN NAME OF ANY FUNCTION
int main()
{
    int age; // DECLARING VARIABLE
    age=21; // INITIALISING VARIABLE (ASSIGNING IT SOME INITIAL VALUES)
    printf("Dhruv %d years old";age); // YOU KNOW WHAT WE DO WITH CONVERGING CHARACTERS
    return 0;
}
